#
# This is free software, license use MIT.
#
# 
# <https://github.com/your-username/your-repo>
#

name: Auto-Update-Mihomo
on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:

jobs:
  update:
    runs-on: Ubuntu-22.04

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Clone the mihomo repository
      run: |
        git clone https://github.com/morytyann/OpenWrt-mihomo.git temp_mihomo
        cd temp_mihomo
        git fetch --all
        git checkout main  # 根据需要选择分支

    - name: Copy updates to the repository
      run: |
        cp -r temp_mihomo/* .  # 将更新的文件复制到当前工作区
        rm -rf temp_mihomo  # 删除临时目录

    - name: Commit and Push changes
      run: |
        git add .
        git commit -m "Auto-update from morytyann/OpenWrt-mihomo"
        git push origin main  # 根据需要选择目标分支
